version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork # Make sure this network is defined in the networks section

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    environment:
      - PORT=${APP_PORT}
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork # Make sure this network is defined in the networks section

networks:
  mynetwork:

volumes:
  pgdata:
